=head1 NAME

camelbot manipulates or gets information from wiki pages

=head1 DESCRIPTION

this program is a CLI tool for automatic editing of MediaWiki pages. one of the 
main tasks is the replacement of external links (urls). furthermore this tool can 
be used to just retrieve information on a MediaWiki.

=head1 MOVED

moved to gitlab: https://gitlab.com/wp-seth/camelbot
